name: SonarQube Analysis
on:
  push:
    branches:
      -main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarqube:
    name: SonarQube Scan
    runs-on: ubuntu-latest
    steps: 
      -uses: action/checkout@v2
      with:
        fetch-depth: 0
      -name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@master
      env:
        SONAR_TOKEN: ${{sqp_ac9f923b127681b2fd152ed8afb2e66d857a4b07}}
        SONAR_HOST_URL: ${{secrets.sonar.core.serverBaseURL
}}
